### ISSUE TITLE
Glowstone Slab Effective Tool

### ISSUE THREAD

**Issue by brisingraerowing** [Brian-Wuest/MC-Repurpose#13]
According to WAILA Harvestability, the effective tool for Glowstone Slabs is a shovel. Is that intended? I would have thought the tool would have been a pickaxe.

**Comment by Brian-Wuest** [comment]
You are right it should not be a shovel. I will still allow the player to break it with their hand but will be more effective with a pickaxe. Pretty sure this is a copy/paste issue frim the dirt slab. Should have this updated tomorow.

**Comment by Brian-Wuest** [comment]
I have released 1.11.0.1 for MC 1.11 to address this issue.

**Comment by brisingraerowing** [comment]
Didn't see this was closed until now. I am still in 1.10.2 as most mods haven't updated yet, and the issue still exists there.

I can easily do a fix myself if you aren't supporting 1.10.2 anymore.

**Comment by Brian-Wuest** [comment]
I still support 1.10.2. I can put this in that version. Might not be until late next week as I am waiting fir Kaojiin to get time to do some textures for me fir a new structure.

**Comment by Brian-Wuest** [comment]
I have updated this for MC-1.10.2

Version 1.10.2.11 is currently being reviewed by CurseForge and should be available soon.

Re-closing this issue.
