### ISSUE TITLE
Crash on startup (RuntimeException)

### ISSUE THREAD

**Issue by brisingraerowing** [Brian-Wuest/MC-Repurpose#9]
[Crash Report](https://gist.github.com/BrisingrAerowing/bd0e3f24321cd2499be556d25f7262b4)

**Comment by brisingraerowing** [comment]
Using a channel name like "MyChannel" is likely to cause major conflicts. I would suggest changing it to "WuestUtilitiesChannel" or something else more unique.

**Comment by Brian-Wuest** [comment]
Hehe. Suprised that hasen't come up before. I can make the change pretty quickly. I will make a similar change to prefab.

**Comment by Brian-Wuest** [comment]
This issue has been fixed with version 1.10.2.8 which is now available on curse forge.

I double checked and Prefab already has a unique message channel. It's called "PrefabChannel".

**Comment by brisingraerowing** [comment]
It still crashes with that particular mod. Not sure what is wrong now.
